### PR TITLE
[WIP] Add Docker Compose support

### PR DESCRIPTION
**Pull request by bdesham**
In order to work on #93 I wanted to add Docker Compose support to this project. This would allow me to stand up the project locally while (hopefully) avoiding all of the pitfalls outlined in the README. This is what I came up with: a setup that runs MySQL 8.0.3 and Redis 3.2.11 along with webmention.io on Ruby 2.5.0.

This PR is marked as WIP because it doesn’t actually work. The services start successfully and the `bundle exec rake db:bootstrap` step seems to complete, but trying to fetch `http://localhost:9019` just gives you an empty reply. I’ve been bashing my head against this for a day now but my unfamiliarity with Ruby and with Rails means that I’m probably not going to get anywhere else without help.

I had to be explicit about which versions of Ruby and Rails to use and I chose the latest: 2.5.0 and 5.1, respectively. Perhaps the problem is that the application is not actually compatible with one or both of these versions and fails silently as a result.

In order to try this out, install Docker Compose and then run `docker-compose up` in the project’s directory. The requisite Docker images will be downloaded or built automatically. To stop it, type Control-C, or run `docker-compose down` in the same directory in another terminal.

### CODE REVIEW

**Comment by aaronpk** [comment]
This project doesn't use Rails at all, maybe that's the problem? I don't use Docker myself, I prefer installing everything natively, but I'd be happy to merge this once it works.

**Comment by bdesham** [comment]
Huh, I’m not sure why I assumed that the project used Rails!

One problem I had was that the web server was trying to bind to 127.0.0.1. Docker didn’t allow this to work but when I changed the address to 0.0.0.0 I was able to get to the site in my browser.

The big problem remaining is that the app never verifies Webmentions that are submitted. It will issue a 201 Created for the initial POST, and it will happily report that a previously-submitted Webmention is “queued for processing,” but it never actually does the processing. I wonder if Docker’s “not quite a full OS” environment is responsible. I tried upgrading sucker_punch to 2.0, since that seemed to be the component that handled the background task, but that didn’t seem to do anything different.

I’ve uploaded my latest work. I’ll keep hacking on this when I have time, although I don’t know when that might be.

**Comment by aaronpk** [comment]
oh yeah, it depends on which ruby server you use to run that. The background processing doesn't run when using `shotgun` for example. On my production server the app is run by Passenger, and that works fine. I'm not quite sure how to translate that into the Docker environment. Probably one of the other ruby web servers would work.

**Comment by bdesham** [comment]
Do you use `start.sh` for production or do you start the app in a different way?

**Comment by aaronpk** [comment]
oh yeah, `start.sh` is what i use for development when i want it to run the background processes. but that makes it so that i have to stop and start that process whenever i change the code. i use `debug.sh` when i want it to load the code on each request, but that kills the background processes. I really need to figure out a better way to run this :)

**Comment by bdesham** [comment]
Ah, okay. I'm not familiar enough with the Ruby ecosystem to know what the most appropriate change would be. I tried replacing thin with WEBrick but that didn't seem to affect the behavior.

**Pull request closed without merging**
